### ISSUE TITLE
Practica2_Interfaz en Visual 

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-equipo-mana#1]
[Practica_2_Equipo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-equipo-mana/files/10750834/Practica_2_Equipo.pdf)

**Comment by Alvaro2-0** [comment]
Execelente trabajo 94.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
